# artifactory-deployment.yaml
apiVersion: apps/v1
kind: Deployment
metadata:
  name: artifactory
  labels:
    app: artifactory
spec:
  replicas: 1
  selector:
    matchLabels:
      app: artifactory
  template:
    metadata:
      labels:
        app: artifactory
    spec:
      initContainers:
        - name: volume-mount-hack
          image: busybox
          command: ["sh", "-c", "chown -R 1030:1030 /var/opt/jfrog/artifactory"]
          volumeMounts:
            - name: artifactory-storage
              mountPath: /var/opt/jfrog/artifactory
      containers:
        - name: artifactory
          image: docker.bintray.io/jfrog/artifactory-oss:latest
          ports:
            - name: http
              containerPort: 8081
            - name: https
              containerPort: 8043
          env:
            - name: DB_TYPE
              value: "postgresql"
            - name: DB_HOST
              value: "postgresql-service"
            - name: DB_PORT
              value: "5432"
            - name: DB_USER
              value: "artifactory_user"
            - name: DB_PASSWORD
              value: "artifactory_password"
            - name: DB_NAME
              value: "artifactory"
          volumeMounts:
            - name: artifactory-storage
              mountPath: /var/opt/jfrog/artifactory
      volumes:
        - name: artifactory-storage
          persistentVolumeClaim:
            claimName: artifactory-pvc