#DO NOT USE, WORKING BUT NOT DOCKER COMMANDS, DOCKER IS NOT EVEN RECOGNIZED IN PIPELINE
apiVersion: apps/v1
kind: Deployment
metadata:
  name: jenkins-agent  # Name of the Jenkins agent deployment
spec:
  replicas: 1  # Number of agent pods you want to run
  selector:
    matchLabels:
      app: jenkins-agent  # Label to identify the agent pod
  template:
    metadata:
      labels:
        app: jenkins-agent  # Label for the agent pod
    spec:
      initContainers:
        # although there is a docker installations, docker execution does not work on this deployment
        - name: docker-installation
          image: busybox  # Use the lightweight BusyBox image
          command: [ "sh", "-c" ]
          args:
            - |
              wget https://download.docker.com/linux/static/stable/x86_64/docker-20.10.7.tgz &&
              tar xzvf docker-20.10.7.tgz &&
              mkdir -p /usr/local/bin &&  # Ensure the target directory exists
              cp docker/* /usr/local/bin/ &&  # Use cp instead of mv
              chmod +x /usr/local/bin/docker* &&
              echo "Docker installed successfully";
      containers:
        - name: jenkins-agent
          image: jenkins/inbound-agent:latest  # Use the Jenkins inbound agent image
          env:
            - name: JENKINS_URL
              #value: "http://192.168.49.2:30002"  # Jenkins service URL (minikube-ip : <exposed jenkins nodePort>) - Does not work
              value: "http://jenkins.local-namespace.svc.cluster.local:8080"  # Jenkins service URL (local) (http://my-svc.my-namespace.svc.cluster.local/<context-path>)
              #See jenkins-deployment.yaml for a more clear picture of exposed ports
            - name: JENKINS_SECRET
              value: "24b2e897364b7e1e1476e012faf9efc0bb0419eb1a574e76cdf5d60731703863"
              # Replace with the agent secret you will generate in step 2
              # Step 2 is in Notion Jenkins Config Page -> Ao criar o node, se se entrar dentro
              # do node, esta la o secret
            - name: JENKINS_AGENT_NAME
              value: "jenkins-agent"  # The name of the agent node in Jenkins

          volumeMounts:
            - name: docker-sock
              mountPath: /var/run/docker.sock  # Mount Docker socket to enable Docker commands
      volumes:
        - name: docker-sock
          hostPath:
            path: /var/run/docker.sock  # Use the host Docker socket