apiVersion: apps/v1
kind: Deployment
metadata:
  name: jenkins-agent  # Name of the Jenkins agent deployment
spec:
  replicas: 1  # Number of agent pods you want to run
  selector:
    matchLabels:
      app: jenkins-agent  # Label to identify the agent pod
  template:
    metadata:
      labels:
        app: jenkins-agent  # Label for the agent pod
    spec:
      initContainers:  # This container runs before the main container to set up Docker socket permissions
        - name: init-docker-sock
          image: busybox  # A minimal image to run basic commands
          #To grant access to docker daemon, without this, the pod will not be able
          #to execute docker commands like build for instance
          command: ['sh', '-c', 'chmod 666 /var/run/docker.sock']
          volumeMounts:
            - name: docker-sock
              mountPath: /var/run/docker.sock
      containers:
        - name: jenkins-agent
          image: nbeites/jenkins-agent-docker:v4  # Use the custom Jenkins inbound agent image present in nbeites DockerHub
          securityContext:
            #It's needed root user to manipulate etc/docker/daemon.json
            runAsUser: 0  # Run as root user
            runAsGroup: 0 # Optional: run as root group
          env:
            - name: JENKINS_URL
              #value: "http://192.168.49.2:30002"  # Jenkins service URL (minikube-ip : <exposed jenkins nodePort>) - Does not work
              value: "http://jenkins.local-namespace.svc.cluster.local:8080"  # Jenkins service URL (local) (http://my-svc.my-namespace.svc.cluster.local/<context-path>)
              #See jenkins-deployment.yaml for a more clear picture of exposed ports
            - name: JENKINS_SECRET
              value: "24b2e897364b7e1e1476e012faf9efc0bb0419eb1a574e76cdf5d60731703863"
              # Replace with the agent secret you will generate in step 2
              # Step 2 is in Notion Jenkins Config Page -> Ao criar o node, se se entrar dentro
              # do node, esta la o secret
            - name: JENKINS_AGENT_NAME
              value: "jenkins-agent"  # The name of the agent node in Jenkins
          volumeMounts:
            - name: docker-sock
              mountPath: /var/run/docker.sock  # Mount Docker socket to enable Docker commands
            - name: docker-config
              mountPath: /etc/docker  # Mount host's /etc/docker directory
      imagePullSecrets:
        - name: dockerhub-secret  # Use the secret for private Docker Hub repositories
          #Needs to be defined in kubernetes:
          #kubectl create secret docker-registry dockerhub-secret --docker-username=nbeites --docker-password=<password> --docker-email=nm.beites@gmail.com
      volumes:
        - name: docker-sock
          hostPath:
            path: /var/run/docker.sock  # Use the host Docker socket
        - name: docker-config
          hostPath:
            path: /etc/docker  # Mount host's /etc/docker directory