apiVersion: v1
kind: PersistentVolume
metadata:
  name: jenkins-pv  # Persistent volume name
spec:
  capacity:
    storage: 10Gi  # Size of the volume
  accessModes:
    - ReadWriteOnce  # Volume can be mounted for read-write by a single pod
  persistentVolumeReclaimPolicy: Retain  # Keeps data even if the PVC is deleted
  hostPath:
    path: /mnt/data/jenkins  # Directory on the node where data will be stored

---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: jenkins-pvc  # Name of the PVC
spec:
  accessModes:
    - ReadWriteOnce  # Volume can only be mounted for read-write by one pod at a time
  resources:
    requests:
      storage: 10Gi  # Request 10Gi of storage for Jenkins