apiVersion: v1
kind: PersistentVolume
metadata:
  name: artifactory-pv
spec:
  capacity:
    storage: 20Gi
  accessModes:
    - ReadWriteOnce
  hostPath:
    path: "C:/tools/kubernetes-volumes/jfrog"  # Path on the host system
    # This is really necessary
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: artifactory-pvc
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 20Gi